### ISSUE TITLE
Can not get it to start

### ISSUE THREAD

**Issue by elearningshow** [jikkuatwork/saddle#1]
I have cloned the git code, I have a windows version of Ollama running. 

I am not sure what the next steps are to run the application, I double clicked on the index.html and the model drop down has no options.  I reviewed some of the code and downloaded the zephyr module.  But, still no luck.

**Comment by jikkuatwork** [comment]
You need to start a server at the root. If you have Python installed its as simple as: `python -m http.server`

**Comment by elearningshow** [comment]
Thank you for getting back to me, that worked and runs fine at http://localhost:8000
