### ISSUE TITLE
Select a default model - Feature Request

### ISSUE THREAD

**Issue by elearningshow** [jikkuatwork/saddle#4]
Currently whatever is the first model in the list is the default model used.  Ideally, I would like to select the default model that will be used.
![saddle_models](https://github.com/jikkuatwork/saddle/assets/766298/32fb6911-bf97-41a8-b522-dbcf566701b9)

**Comment by jikkuatwork** [comment]
That cannot be done. There is no memory for the program, everything is temporary in memory. Its done intentionally for the simplicity/privacy,
